// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.5
// Generated from: nitro_server.native.dart
// spec-sha256: 13efce96720a5dd48faaa5fa4afb1c94e4cec9bca91cbab89c96a7e8273214b9
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#ifndef NITRO_EXPORT
#  if defined(_WIN32)
#    define NITRO_EXPORT __declspec(dllexport)
#  else
#    define NITRO_EXPORT __attribute__((visibility("default"))) __attribute__((used))
#  endif
#endif

#ifndef NITRO_ERROR_DEFINED
#define NITRO_ERROR_DEFINED
typedef struct {
  int8_t hasError;
  const char* name;
  const char* message;
  const char* code;
  const char* stackTrace;
} NitroError;
#endif

#ifndef NITRO_OPT_DEFINED
#define NITRO_OPT_DEFINED
#pragma pack(push, 1)
typedef struct { uint8_t hasValue; int64_t  value; } NitroOptInt64;
typedef struct { uint8_t hasValue; double   value; } NitroOptFloat64;
typedef struct { uint8_t hasValue; uint8_t  value; } NitroOptBool;
#pragma pack(pop)
#endif

// --- Enums ---
typedef enum {
  RAWSERVERMETHOD_GET = 0,
  RAWSERVERMETHOD_HEAD = 1,
  RAWSERVERMETHOD_POST = 2,
  RAWSERVERMETHOD_PUT = 3,
  RAWSERVERMETHOD_DELETE = 4,
  RAWSERVERMETHOD_PATCH = 5,
  RAWSERVERMETHOD_OPTIONS = 6,
  RAWSERVERMETHOD_TRACE = 7,
  RAWSERVERMETHOD_ALL = 8,
  RAWSERVERMETHOD_CUSTOM = 9,
} RawServerMethod;

typedef enum {
  RAWSERVERERRORKIND_NONE = 0,
  RAWSERVERERRORKIND_ALREADY_RUNNING = 1,
  RAWSERVERERRORKIND_NOT_RUNNING = 2,
  RAWSERVERERRORKIND_BIND_FAILED = 3,
  RAWSERVERERRORKIND_TLS_ERROR = 4,
  RAWSERVERERRORKIND_ROUTE_NOT_FOUND = 5,
  RAWSERVERERRORKIND_HANDLER_TIMEOUT = 6,
  RAWSERVERERRORKIND_REQUEST_TOO_LARGE = 7,
  RAWSERVERERRORKIND_RESPONSE_TOO_LARGE = 8,
  RAWSERVERERRORKIND_IO = 9,
  RAWSERVERERRORKIND_BAD_REQUEST = 10,
  RAWSERVERERRORKIND_UNKNOWN = 11,
} RawServerErrorKind;

typedef enum {
  RAWBODYKIND_DATA = 0,
  RAWBODYKIND_END = 1,
  RAWBODYKIND_ERROR = 2,
} RawBodyKind;

typedef enum {
  RAWSERVEREVENTKIND_STARTED = 0,
  RAWSERVEREVENTKIND_STOPPED = 1,
  RAWSERVEREVENTKIND_HANDLER_TIMEOUT = 2,
  RAWSERVEREVENTKIND_CLIENT_ERROR = 3,
  RAWSERVEREVENTKIND_NOTICE = 4,
} RawServerEventKind;

// --- Structs ---
#ifndef NITRO_STRUCT_RAWBODYCHUNK_DEFINED
#define NITRO_STRUCT_RAWBODYCHUNK_DEFINED
typedef struct {
  uint8_t* bytes; /* zero-copy */
  int64_t bytesLength; /* synthesized: element count for zero-copy buffer */
  int64_t requestId; 
  int64_t kind; 
  int64_t aux; 
} RawBodyChunk;
#endif // NITRO_STRUCT_RAWBODYCHUNK_DEFINED

#ifdef __cplusplus
extern "C" {
#endif

NITRO_EXPORT uint32_t nitro_server_nitro_abi_version(void);
NITRO_EXPORT const char* nitro_server_nitro_bridge_checksum(void);
NITRO_EXPORT intptr_t nitro_server_init_dart_api_dl(void* data);
NITRO_EXPORT NitroError* nitro_server_get_error(void);
NITRO_EXPORT void nitro_server_clear_error(void);
NITRO_EXPORT int64_t nitro_server_create_instance(const char* key);
NITRO_EXPORT void nitro_server_destroy_instance(int64_t instanceId);
NITRO_EXPORT void nitro_server_nitro_free(void* ptr);
NITRO_EXPORT void* nitro_server_nitro_alloc(size_t size);



// Methods
NITRO_EXPORT const char* nitro_server_engine_version(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT int8_t nitro_server_supports_tls(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_server_reset_native(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_server_configure_server(int64_t instanceId, void* config, NitroError* _nitro_err);
NITRO_EXPORT void* nitro_server_register_route(int64_t instanceId, void* route, NitroError* _nitro_err);
NITRO_EXPORT void* nitro_server_unregister_route(int64_t instanceId, const char* method, const char* pattern, NitroError* _nitro_err);
NITRO_EXPORT void* nitro_server_start(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_server_stop(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_server_respond(int64_t instanceId, int64_t requestId, int64_t status, void* headers, uint8_t* body, size_t body_length, NitroError* _nitro_err);
NITRO_EXPORT void nitro_server_ack_body(int64_t instanceId, int64_t requestId, int64_t ackedChunks, NitroError* _nitro_err);
NITRO_EXPORT void nitro_server_start_stream(int64_t instanceId, int64_t requestId, int64_t status, void* headers, NitroError* _nitro_err);
NITRO_EXPORT void nitro_server_send_stream_chunk(int64_t instanceId, int64_t requestId, uint8_t* chunk, size_t chunk_length, int8_t last, NitroError* _nitro_err);

// Streams
// Stream<RawIncomingRequest> incomingRequests
NITRO_EXPORT void nitro_server_register_incoming_requests_stream(int64_t instanceId, int64_t dart_port);
NITRO_EXPORT void nitro_server_release_incoming_requests_stream(int64_t dart_port);
// Stream<RawBodyChunk> bodyChunks
NITRO_EXPORT void nitro_server_register_body_chunks_stream(int64_t instanceId, int64_t dart_port);
NITRO_EXPORT void nitro_server_release_body_chunks_stream(int64_t dart_port);
// Stream<RawServerEvent> serverEvents
NITRO_EXPORT void nitro_server_register_server_events_stream(int64_t instanceId, int64_t dart_port);
NITRO_EXPORT void nitro_server_release_server_events_stream(int64_t dart_port);

// Struct release functions
NITRO_EXPORT void nitro_server_release_RawBodyChunk(void* ptr);

#ifdef __cplusplus
}
#endif
