// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.5
// Generated from: nitro_server.native.dart
// spec-sha256: 47175e48659bf884e5fadab4993265e464645da48776a2ad3f179c3b5bfe1ff9
// ignore_for_file: no_leading_underscores_for_local_identifiers, prefer_typing_uninitialized_variables, non_constant_identifier_names, unused_element, unused_field
part of 'nitro_server.native.dart';

// --- Enum FFI helpers (generated by Nitrogen) ---

extension RawServerMethodNativeExt on RawServerMethod {
  int get nativeValue => index + 0;
}

extension RawServerMethodFromNativeExt on int {
  RawServerMethod toRawServerMethod() => RawServerMethod.values[this - 0];
}

extension RawServerErrorKindNativeExt on RawServerErrorKind {
  int get nativeValue => index + 0;
}

extension RawServerErrorKindFromNativeExt on int {
  RawServerErrorKind toRawServerErrorKind() =>
      RawServerErrorKind.values[this - 0];
}

extension RawBodyKindNativeExt on RawBodyKind {
  int get nativeValue => index + 0;
}

extension RawBodyKindFromNativeExt on int {
  RawBodyKind toRawBodyKind() => RawBodyKind.values[this - 0];
}

extension RawServerEventKindNativeExt on RawServerEventKind {
  int get nativeValue => index + 0;
}

extension RawServerEventKindFromNativeExt on int {
  RawServerEventKind toRawServerEventKind() =>
      RawServerEventKind.values[this - 0];
}

// --- Struct FFI representations (generated by Nitrogen) ---

final class RawBodyChunkFfi extends Struct {
  external Pointer<Uint8> bytes;
  @Int64()
  external int bytesLength;
  @Int64()
  external int requestId;
  @Int64()
  external int kind;
  @Int64()
  external int aux;
}

extension RawBodyChunkFfiExt on RawBodyChunkFfi {
  RawBodyChunk toDart() {
    return RawBodyChunk(
      bytes: Uint8List.fromList(bytes.asTypedList(bytesLength)),
      requestId: requestId,
      kind: kind,
      aux: aux,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  ///
  /// [nativeFree] must be the free function matching the allocator that
  /// produced the fields — for native-returned structs, the module's
  /// `_nitroFree` (the exported C-runtime free). package:ffi's malloc.free
  /// is CoTaskMemFree on Windows and corrupts the heap on these pointers.
  void freeFields(void Function(Pointer<NativeType>) nativeFree) {}
}

extension RawBodyChunkExt on RawBodyChunk {
  Pointer<RawBodyChunkFfi> toNative(Arena arena) {
    final ptr = arena<RawBodyChunkFfi>();
    ptr.ref.bytes = bytes.toPointer(arena);
    ptr.ref.bytesLength = bytes.length;
    ptr.ref.requestId = requestId;
    ptr.ref.kind = kind;
    ptr.ref.aux = aux;
    return ptr;
  }
}

final class RawWsMessageFfi extends Struct {
  external Pointer<Uint8> payload;
  @Int64()
  external int payloadLength;
  @Int64()
  external int connectionId;
  @Int64()
  external int kind;
  @Int64()
  external int aux;
}

extension RawWsMessageFfiExt on RawWsMessageFfi {
  RawWsMessage toDart() {
    return RawWsMessage(
      payload: Uint8List.fromList(payload.asTypedList(payloadLength)),
      connectionId: connectionId,
      kind: kind,
      aux: aux,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  ///
  /// [nativeFree] must be the free function matching the allocator that
  /// produced the fields — for native-returned structs, the module's
  /// `_nitroFree` (the exported C-runtime free). package:ffi's malloc.free
  /// is CoTaskMemFree on Windows and corrupts the heap on these pointers.
  void freeFields(void Function(Pointer<NativeType>) nativeFree) {}
}

extension RawWsMessageExt on RawWsMessage {
  Pointer<RawWsMessageFfi> toNative(Arena arena) {
    final ptr = arena<RawWsMessageFfi>();
    ptr.ref.payload = payload.toPointer(arena);
    ptr.ref.payloadLength = payload.length;
    ptr.ref.connectionId = connectionId;
    ptr.ref.kind = kind;
    ptr.ref.aux = aux;
    return ptr;
  }
}

// --- Struct Native Proxies (zero-copy, lazy field access) ---

/// Zero-copy proxy for [RawBodyChunk].
/// Extends [RawBodyChunk] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `RawBodyChunkProxy <: RawBodyChunk`, a `Stream<RawBodyChunkProxy>`
/// satisfies `Stream<RawBodyChunk>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_server_release_RawBodyChunk'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class RawBodyChunkProxy extends RawBodyChunk implements Finalizable {
  final Pointer<RawBodyChunkFfi> _native;

  static NativeFinalizer? _finalizer;
  static void Function(Pointer<Void>)? _releaseFn;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_server_release_RawBodyChunk',
      ),
    );
    _releaseFn ??= dylib
        .lookupFunction<
          Void Function(Pointer<Void>),
          void Function(Pointer<Void>)
        >('nitro_server_release_RawBodyChunk');
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  RawBodyChunkProxy(this._native)
    : super(bytes: Uint8List(0), requestId: 0, kind: 0, aux: 0) {
    assert(
      _finalizer != null,
      'RawBodyChunkProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(
      this,
      _native.cast(),
      detach: this,
      externalSize: sizeOf<RawBodyChunkFfi>(),
    );
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  Uint8List get bytes => _native.ref.bytes.asTypedList(_native.ref.bytesLength);
  @override
  int get requestId => _native.ref.requestId;
  @override
  int get kind => _native.ref.kind;
  @override
  int get aux => _native.ref.aux;

  /// Eagerly copies all fields to a plain [RawBodyChunk] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  RawBodyChunk toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    _releaseFn!(_native.cast());
    return v;
  }
}

/// Zero-copy proxy for [RawWsMessage].
/// Extends [RawWsMessage] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `RawWsMessageProxy <: RawWsMessage`, a `Stream<RawWsMessageProxy>`
/// satisfies `Stream<RawWsMessage>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_server_release_RawWsMessage'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class RawWsMessageProxy extends RawWsMessage implements Finalizable {
  final Pointer<RawWsMessageFfi> _native;

  static NativeFinalizer? _finalizer;
  static void Function(Pointer<Void>)? _releaseFn;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_server_release_RawWsMessage',
      ),
    );
    _releaseFn ??= dylib
        .lookupFunction<
          Void Function(Pointer<Void>),
          void Function(Pointer<Void>)
        >('nitro_server_release_RawWsMessage');
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  RawWsMessageProxy(this._native)
    : super(payload: Uint8List(0), connectionId: 0, kind: 0, aux: 0) {
    assert(
      _finalizer != null,
      'RawWsMessageProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(
      this,
      _native.cast(),
      detach: this,
      externalSize: sizeOf<RawWsMessageFfi>(),
    );
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  Uint8List get payload =>
      _native.ref.payload.asTypedList(_native.ref.payloadLength);
  @override
  int get connectionId => _native.ref.connectionId;
  @override
  int get kind => _native.ref.kind;
  @override
  int get aux => _native.ref.aux;

  /// Eagerly copies all fields to a plain [RawWsMessage] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  RawWsMessage toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    _releaseFn!(_native.cast());
    return v;
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension RawHeaderRecordExt on RawHeader {
  static RawHeader fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawHeader fromReader(RecordReader r) =>
      RawHeader(name: r.readString(), value: r.readString());

  void writeFields(RecordWriter writer) {
    writer.writeString(name);
    writer.writeString(value);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawRouteParamRecordExt on RawRouteParam {
  static RawRouteParam fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawRouteParam fromReader(RecordReader r) =>
      RawRouteParam(name: r.readString(), value: r.readString());

  void writeFields(RecordWriter writer) {
    writer.writeString(name);
    writer.writeString(value);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawTlsConfigRecordExt on RawTlsConfig {
  static RawTlsConfig fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawTlsConfig fromReader(RecordReader r) => RawTlsConfig(
    certPem: r.readString(),
    keyPem: r.readString(),
    certFile: r.readString(),
    keyFile: r.readString(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(certPem);
    writer.writeString(keyPem);
    writer.writeString(certFile);
    writer.writeString(keyFile);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawServerConfigRecordExt on RawServerConfig {
  static RawServerConfig fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawServerConfig fromReader(RecordReader r) => RawServerConfig(
    host: r.readString(),
    port: r.readInt(),
    backlog: r.readInt(),
    maxBodyBytes: r.readInt(),
    defaultTimeoutMs: r.readInt(),
    keepAliveTimeoutMs: r.readInt(),
    maxRequestsPerConn: r.readInt(),
    workerThreads: r.readInt(),
    maxConnections: r.readInt(),
    maxConnectionsPerIp: r.readInt(),
    headerTimeoutMs: r.readInt(),
    writeTimeoutMs: r.readInt(),
    wsMaxBufferBytes: r.readInt(),
    wsCompression: r.readBool(),
    tls: RawTlsConfigRecordExt.fromReader(r),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(host);
    writer.writeInt(port);
    writer.writeInt(backlog);
    writer.writeInt(maxBodyBytes);
    writer.writeInt(defaultTimeoutMs);
    writer.writeInt(keepAliveTimeoutMs);
    writer.writeInt(maxRequestsPerConn);
    writer.writeInt(workerThreads);
    writer.writeInt(maxConnections);
    writer.writeInt(maxConnectionsPerIp);
    writer.writeInt(headerTimeoutMs);
    writer.writeInt(writeTimeoutMs);
    writer.writeInt(wsMaxBufferBytes);
    writer.writeBool(wsCompression);
    tls.writeFields(writer);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawRouteConfigRecordExt on RawRouteConfig {
  static RawRouteConfig fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawRouteConfig fromReader(RecordReader r) => RawRouteConfig(
    method: r.readInt().toRawServerMethod(),
    customMethod: r.readString(),
    pattern: r.readString(),
    timeoutMs: r.readInt(),
    isWebSocket: r.readBool(),
    streamBody: r.readBool(),
    maxBodyBytes: r.readInt(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(method.nativeValue);
    writer.writeString(customMethod);
    writer.writeString(pattern);
    writer.writeInt(timeoutMs);
    writer.writeBool(isWebSocket);
    writer.writeBool(streamBody);
    writer.writeInt(maxBodyBytes);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawServerStatusRecordExt on RawServerStatus {
  static RawServerStatus fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawServerStatus fromReader(RecordReader r) => RawServerStatus(
    errorKind: r.readInt().toRawServerErrorKind(),
    errorMessage: r.readString(),
    boundPort: r.readInt(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(errorKind.nativeValue);
    writer.writeString(errorMessage);
    writer.writeInt(boundPort);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawIncomingRequestRecordExt on RawIncomingRequest {
  static RawIncomingRequest fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawIncomingRequest fromReader(RecordReader r) => RawIncomingRequest(
    requestId: r.readInt(),
    method: r.readInt().toRawServerMethod(),
    customMethod: r.readString(),
    path: r.readString(),
    query: r.readString(),
    headers: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
    contentLength: r.readInt(),
    hasBody: r.readBool(),
    bodyComplete: r.readBool(),
    routePattern: r.readString(),
    params: List.generate(
      r.readInt32(),
      (_) => RawRouteParamRecordExt.fromReader(r),
    ),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(requestId);
    writer.writeInt(method.nativeValue);
    writer.writeString(customMethod);
    writer.writeString(path);
    writer.writeString(query);
    writer.writeInt32(headers.length);
    for (final e in headers) {
      e.writeFields(writer);
    }
    writer.writeInt(contentLength);
    writer.writeBool(hasBody);
    writer.writeBool(bodyComplete);
    writer.writeString(routePattern);
    writer.writeInt32(params.length);
    for (final e in params) {
      e.writeFields(writer);
    }
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawServerEventRecordExt on RawServerEvent {
  static RawServerEvent fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawServerEvent fromReader(RecordReader r) => RawServerEvent(
    kind: r.readInt(),
    requestId: r.readInt(),
    message: r.readString(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(kind);
    writer.writeInt(requestId);
    writer.writeString(message);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

class _NitroServerNativeImpl extends NitroServerNative {
  final DynamicLibrary _dylib;
  static final _instances = <String, WeakReference<_NitroServerNativeImpl>>{};

  static final _instanceFinalizer =
      Finalizer<
        ({
          int id,
          String key,
          Pointer<NitroErrorFfi> err,
          void Function(int) destroy,
        })
      >((t) {
        try {
          t.destroy(t.id);
          NitroRuntime.releaseLib('nitro_server');
          if (_instances[t.key]?.target == null) _instances.remove(t.key);
        } catch (_) {
        } finally {
          calloc.free(t.err);
        }
      });
  final String _instanceKey;
  late final int _instanceId;
  final Pointer<NitroErrorFfi> _nitroErr = calloc<NitroErrorFfi>();
  late final void Function(Pointer<Void>) _nitroFreePtr = _dylib
      .lookupFunction<
        Void Function(Pointer<Void>),
        void Function(Pointer<Void>)
      >('nitro_server_nitro_free');
  void _nitroFree(Pointer<NativeType> ptr) => _nitroFreePtr(ptr.cast());
  late final Pointer<NativeFinalizerFunction> _nitroFreeFinalizer = _dylib
      .lookup<NativeFinalizerFunction>('nitro_server_nitro_free')
      .cast();
  late final Pointer<Void> Function(int) _nitroAllocPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(IntPtr),
        Pointer<Void> Function(int)
      >('nitro_server_nitro_alloc');
  late final NitroNativeAllocator _nitroNativeAllocator = NitroNativeAllocator(
    _nitroAllocPtr,
    _nitroFreePtr,
  );

  static DynamicLibrary _loadSupportedLibrary() {
    return NitroRuntime.loadLibForTargets(
      'nitro_server',
      ios: true,
      android: true,
      macos: true,
      windows: true,
      linux: true,
      web: false,
    );
  }

  factory _NitroServerNativeImpl([String key = 'default']) {
    final cached = _instances[key]?.target;
    if (cached != null) return cached;
    return _NitroServerNativeImpl._init(key);
  }

  _NitroServerNativeImpl._init(this._instanceKey)
    : _dylib = _loadSupportedLibrary() {
    final initSw = Stopwatch()..start();
    assert(
      sizeOf<IntPtr>() >= 4,
      'nitro_server: unsupported pointer width ${sizeOf<IntPtr>()}B',
    );
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('nitro_server_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
        'nitro_server: Dart API DL initialization failed with code $initCode.',
      );
    }
    if (!_dylib.providesSymbol('nitro_server_nitro_abi_version')) {
      throw StateError(
        'nitro_server: missing nitro_server_nitro_abi_version — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkAbiVersion(
      'nitro_server',
      () => _dylib.lookupFunction<Uint32 Function(), int Function()>(
        'nitro_server_nitro_abi_version',
      )(),
    );
    if (!_dylib.providesSymbol('nitro_server_nitro_bridge_checksum')) {
      throw StateError(
        'nitro_server: missing nitro_server_nitro_bridge_checksum — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkLinkChecksum(
      'nitro_server',
      'a6ec080af69a3c54',
      () => _dylib
          .lookupFunction<Pointer<Utf8> Function(), Pointer<Utf8> Function()>(
            'nitro_server_nitro_bridge_checksum',
          )()
          .toDartString(),
    );
    RawBodyChunkProxy._init(_dylib);
    RawWsMessageProxy._init(_dylib);
    final _keyPtr = _instanceKey.toNativeUtf8(allocator: calloc);
    try {
      _instanceId = _createInstancePtr(_keyPtr);
      if (_instanceId < 0) {
        throw StateError(
          'nitro_server: failed to create native instance for key "$_instanceKey".',
        );
      }
    } finally {
      calloc.free(_keyPtr);
    }
    NitroInstanceRegistry.register(_instanceId, this);
    _instances[_instanceKey] = WeakReference(this);
    _instanceFinalizer.attach(this, (
      id: _instanceId,
      key: _instanceKey,
      err: _nitroErr,
      destroy: _destroyInstancePtr,
    ), detach: this);
    initSw.stop();
    NitroRuntime.logLifecycle(
      'init(nitro_server)',
      'initialized in ${initSw.elapsedMicroseconds} µs (instanceId=$_instanceId)',
    );
  }

  late final int Function(Pointer<Utf8>) _createInstancePtr = _dylib
      .lookupFunction<
        Int64 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_server_create_instance');
  late final void Function(int) _destroyInstancePtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_server_destroy_instance',
      );
  late final Pointer<Utf8> Function(int, Pointer<NitroErrorFfi>)
  _engineVersionPtr = _dylib
      .lookupFunction<
        Pointer<Utf8> Function(Int64, Pointer<NitroErrorFfi>),
        Pointer<Utf8> Function(int, Pointer<NitroErrorFfi>)
      >('nitro_server_engine_version');
  late final bool Function(int, Pointer<NitroErrorFfi>) _supportsTlsPtr = _dylib
      .lookup<NativeFunction<Bool Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_server_supports_tls',
      )
      .asFunction<bool Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<NitroErrorFfi>) _resetNativePtr = _dylib
      .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_server_reset_native',
      )
      .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>)
  _configureServerPtr = _dylib
      .lookupFunction<
        Void Function(Int64, Pointer<Uint8>, Pointer<NitroErrorFfi>),
        void Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>)
      >('nitro_server_configure_server');
  late final Pointer<Uint8> Function(
    int,
    Pointer<Uint8>,
    Pointer<NitroErrorFfi>,
  )
  _registerRoutePtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Int64, Pointer<Uint8>, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>)
      >('nitro_server_register_route');
  late final Pointer<Uint8> Function(
    int,
    Pointer<Utf8>,
    Pointer<Utf8>,
    Pointer<NitroErrorFfi>,
  )
  _unregisterRoutePtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(
          Int64,
          Pointer<Utf8>,
          Pointer<Utf8>,
          Pointer<NitroErrorFfi>,
        ),
        Pointer<Uint8> Function(
          int,
          Pointer<Utf8>,
          Pointer<Utf8>,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_server_unregister_route');
  late final Pointer<Uint8> Function(int, Pointer<NitroErrorFfi>) _startPtr =
      _dylib.lookupFunction<
        Pointer<Uint8> Function(Int64, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(int, Pointer<NitroErrorFfi>)
      >('nitro_server_start');
  late final void Function(int, Pointer<NitroErrorFfi>) _stopPtr = _dylib
      .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_server_stop',
      )
      .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<NitroErrorFfi>) _beginDrainPtr = _dylib
      .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_server_begin_drain',
      )
      .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final int Function(int, Pointer<NitroErrorFfi>)
  _inFlightRequestsPtr = _dylib
      .lookup<NativeFunction<Int64 Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_server_in_flight_requests',
      )
      .asFunction<int Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final int Function(int, Pointer<NitroErrorFfi>)
  _liveConnectionsPtr = _dylib
      .lookup<NativeFunction<Int64 Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_server_live_connections',
      )
      .asFunction<int Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(
    int,
    int,
    int,
    Pointer<Uint8>,
    Pointer<Utf8>,
    int,
    int,
    Pointer<NitroErrorFfi>,
  )
  _respondFilePtr = _dylib
      .lookupFunction<
        Void Function(
          Int64,
          Int64,
          Int64,
          Pointer<Uint8>,
          Pointer<Utf8>,
          Int64,
          Int64,
          Pointer<NitroErrorFfi>,
        ),
        void Function(
          int,
          int,
          int,
          Pointer<Uint8>,
          Pointer<Utf8>,
          int,
          int,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_server_respond_file');
  late final void Function(
    int,
    int,
    int,
    Pointer<Uint8>,
    Pointer<Uint8>,
    int,
    Pointer<NitroErrorFfi>,
  )
  _respondPtr = _dylib
      .lookupFunction<
        Void Function(
          Int64,
          Int64,
          Int64,
          Pointer<Uint8>,
          Pointer<Uint8>,
          Size,
          Pointer<NitroErrorFfi>,
        ),
        void Function(
          int,
          int,
          int,
          Pointer<Uint8>,
          Pointer<Uint8>,
          int,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_server_respond');
  late final void Function(int, int, int, Pointer<NitroErrorFfi>) _ackBodyPtr =
      _dylib
          .lookup<
            NativeFunction<
              Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
            >
          >('nitro_server_ack_body')
          .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
            isLeaf: true,
          );
  late final void Function(
    int,
    int,
    int,
    Pointer<Uint8>,
    Pointer<NitroErrorFfi>,
  )
  _startStreamPtr = _dylib
      .lookupFunction<
        Void Function(
          Int64,
          Int64,
          Int64,
          Pointer<Uint8>,
          Pointer<NitroErrorFfi>,
        ),
        void Function(int, int, int, Pointer<Uint8>, Pointer<NitroErrorFfi>)
      >('nitro_server_start_stream');
  late final void Function(
    int,
    int,
    Pointer<Uint8>,
    int,
    bool,
    Pointer<NitroErrorFfi>,
  )
  _sendStreamChunkPtr = _dylib
      .lookupFunction<
        Void Function(
          Int64,
          Int64,
          Pointer<Uint8>,
          Size,
          Bool,
          Pointer<NitroErrorFfi>,
        ),
        void Function(
          int,
          int,
          Pointer<Uint8>,
          int,
          bool,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_server_send_stream_chunk');
  late final int Function(
    int,
    int,
    Pointer<Uint8>,
    int,
    bool,
    bool,
    Pointer<NitroErrorFfi>,
  )
  _wsSendPtr = _dylib
      .lookupFunction<
        Int64 Function(
          Int64,
          Int64,
          Pointer<Uint8>,
          Size,
          Bool,
          Bool,
          Pointer<NitroErrorFfi>,
        ),
        int Function(
          int,
          int,
          Pointer<Uint8>,
          int,
          bool,
          bool,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_server_ws_send');
  late final void Function(int, int, int, Pointer<NitroErrorFfi>) _wsClosePtr =
      _dylib
          .lookup<
            NativeFunction<
              Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
            >
          >('nitro_server_ws_close')
          .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
            isLeaf: true,
          );
  late final void Function(int, int) _registerIncomingRequestsPtr = _dylib
      .lookupFunction<Void Function(Int64, Int64), void Function(int, int)>(
        'nitro_server_register_incoming_requests_stream',
      );
  late final void Function(int) _releaseIncomingRequestsPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_server_release_incoming_requests_stream',
      );
  late final void Function(int, int) _registerBodyChunksPtr = _dylib
      .lookupFunction<Void Function(Int64, Int64), void Function(int, int)>(
        'nitro_server_register_body_chunks_stream',
      );
  late final void Function(int) _releaseBodyChunksPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_server_release_body_chunks_stream',
      );
  late final void Function(int, int) _registerServerEventsPtr = _dylib
      .lookupFunction<Void Function(Int64, Int64), void Function(int, int)>(
        'nitro_server_register_server_events_stream',
      );
  late final void Function(int) _releaseServerEventsPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_server_release_server_events_stream',
      );
  late final void Function(int, int) _registerWsMessagesPtr = _dylib
      .lookupFunction<Void Function(Int64, Int64), void Function(int, int)>(
        'nitro_server_register_ws_messages_stream',
      );
  late final void Function(int) _releaseWsMessagesPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_server_release_ws_messages_stream',
      );
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib
      .lookupFunction<
        Pointer<NitroErrorFfi> Function(),
        Pointer<NitroErrorFfi> Function()
      >('nitro_server_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>(
        'nitro_server_clear_error',
      );

  @override
  void dispose() {
    if (isDisposed) return;
    _instanceFinalizer.detach(this);
    NitroRuntime.logLifecycle(
      'dispose(nitro_server)',
      'disposing (instanceId=$_instanceId)',
    );
    _destroyInstancePtr(_instanceId);
    NitroRuntime.releaseLib('nitro_server');
    _instances.remove(_instanceKey);
    NitroInstanceRegistry.unregister(_instanceId, this);
    calloc.free(_nitroErr); // S8: free pre-allocated error slot
    super.dispose(); // sets isDisposed = true, calls onDestroy()
    NitroRuntime.logLifecycle('dispose(nitro_server)', 'disposed');
  }

  /// Opaque reference to this native impl — pass to other plugins via AnyNativeObject.
  AnyNativeObject get asAnyNativeObject => AnyNativeObject(_instanceId);

  @override
  String engineVersion() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _engineVersionPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res.toDartStringBorrowed();
    }, methodName: 'engineVersion');
  }

  @override
  bool supportsTls() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _supportsTlsPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'supportsTls');
  }

  @override
  void resetNative() {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _resetNativePtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'resetNative');
  }

  @override
  void configureServer(RawServerConfig config) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _configureServerPtr(_instanceId, config.toNative(arena), _nitroErr);
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      }),
      methodName: 'configureServer',
    );
  }

  @override
  RawServerStatus registerRoute(RawRouteConfig route) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _registerRoutePtr(
          _instanceId,
          route.toNative(arena),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
        final RawServerStatus decoded;
        try {
          decoded = RawServerStatusRecordExt.fromNative(res);
        } finally {
          _nitroFree(res);
        }
        return decoded;
      }),
      methodName: 'registerRoute',
    );
  }

  @override
  RawServerStatus unregisterRoute(String method, String pattern) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _unregisterRoutePtr(
          _instanceId,
          method.toNativeUtf8(allocator: arena),
          pattern.toNativeUtf8(allocator: arena),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
        final RawServerStatus decoded;
        try {
          decoded = RawServerStatusRecordExt.fromNative(res);
        } finally {
          _nitroFree(res);
        }
        return decoded;
      }),
      methodName: 'unregisterRoute',
    );
  }

  @override
  RawServerStatus start() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _startPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      final RawServerStatus decoded;
      try {
        decoded = RawServerStatusRecordExt.fromNative(res);
      } finally {
        _nitroFree(res);
      }
      return decoded;
    }, methodName: 'start');
  }

  @override
  void stop() {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _stopPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'stop');
  }

  @override
  void beginDrain() {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _beginDrainPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'beginDrain');
  }

  @override
  int inFlightRequests() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _inFlightRequestsPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'inFlightRequests');
  }

  @override
  int liveConnections() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _liveConnectionsPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'liveConnections');
  }

  @override
  void respondFile(
    int requestId,
    int status,
    List<RawHeader> headers,
    String path,
    int offset,
    int length,
  ) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _respondFilePtr(
          _instanceId,
          requestId,
          status,
          RecordWriter.encodeIndexedList(
            headers,
            (w, e) => e.writeFields(w),
            arena,
          ),
          path.toNativeUtf8(allocator: arena),
          offset,
          length,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      }),
      methodName: 'respondFile',
    );
  }

  @override
  void respond(
    int requestId,
    int status,
    List<RawHeader> headers,
    Uint8List body,
  ) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _respondPtr(
          _instanceId,
          requestId,
          status,
          RecordWriter.encodeIndexedList(
            headers,
            (w, e) => e.writeFields(w),
            arena,
          ),
          body.toPointer(arena),
          body.length,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      }),
      methodName: 'respond',
    );
  }

  @override
  void ackBody(int requestId, int ackedChunks) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _ackBodyPtr(_instanceId, requestId, ackedChunks, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'ackBody');
  }

  @override
  void startStream(int requestId, int status, List<RawHeader> headers) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _startStreamPtr(
          _instanceId,
          requestId,
          status,
          RecordWriter.encodeIndexedList(
            headers,
            (w, e) => e.writeFields(w),
            arena,
          ),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      }),
      methodName: 'startStream',
    );
  }

  @override
  void sendStreamChunk(int requestId, Uint8List chunk, bool last) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _sendStreamChunkPtr(
          _instanceId,
          requestId,
          chunk.toPointer(arena),
          chunk.length,
          last,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      }),
      methodName: 'sendStreamChunk',
    );
  }

  @override
  int wsSend(
    int connectionId,
    Uint8List payload,
    bool binary,
    bool compressed,
  ) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _wsSendPtr(
          _instanceId,
          connectionId,
          payload.toPointer(arena),
          payload.length,
          binary,
          compressed,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
        return res;
      }),
      methodName: 'wsSend',
    );
  }

  @override
  void wsClose(int connectionId, int code) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _wsClosePtr(_instanceId, connectionId, code, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'wsClose');
  }

  @override
  Stream<RawIncomingRequest> get incomingRequests {
    checkDisposed();
    return NitroRuntime.openStream<RawIncomingRequest>(
      register: (port) => _registerIncomingRequestsPtr(_instanceId, port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream incomingRequests',
          );
        }
        final rawPtr = Pointer<Uint8>.fromAddress(message as int);
        try {
          return RawIncomingRequestRecordExt.fromNative(rawPtr);
        } finally {
          _nitroFree(rawPtr);
        }
      },
      release: (port) => _releaseIncomingRequestsPtr(port),
      backpressure: Backpressure.bufferDrop,
    );
  }

  @override
  Stream<RawBodyChunk> get bodyChunks {
    checkDisposed();
    return NitroRuntime.openStream<RawBodyChunkProxy>(
      register: (port) => _registerBodyChunksPtr(_instanceId, port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream bodyChunks',
          );
        }
        return RawBodyChunkProxy(
          Pointer<RawBodyChunkFfi>.fromAddress(message as int),
        );
      },
      release: (port) => _releaseBodyChunksPtr(port),
      backpressure: Backpressure.bufferDrop,
    );
  }

  @override
  Stream<RawServerEvent> get serverEvents {
    checkDisposed();
    return NitroRuntime.openStream<RawServerEvent>(
      register: (port) => _registerServerEventsPtr(_instanceId, port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream serverEvents',
          );
        }
        final rawPtr = Pointer<Uint8>.fromAddress(message as int);
        try {
          return RawServerEventRecordExt.fromNative(rawPtr);
        } finally {
          _nitroFree(rawPtr);
        }
      },
      release: (port) => _releaseServerEventsPtr(port),
      backpressure: Backpressure.bufferDrop,
    );
  }

  @override
  Stream<RawWsMessage> get wsMessages {
    checkDisposed();
    return NitroRuntime.openStream<RawWsMessageProxy>(
      register: (port) => _registerWsMessagesPtr(_instanceId, port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream wsMessages',
          );
        }
        return RawWsMessageProxy(
          Pointer<RawWsMessageFfi>.fromAddress(message as int),
        );
      },
      release: (port) => _releaseWsMessagesPtr(port),
      backpressure: Backpressure.bufferDrop,
    );
  }
}

extension NitroServerNativeNativeRef on NitroServerNative {
  AnyNativeObject get asAnyNativeObject =>
      (this as _NitroServerNativeImpl).asAnyNativeObject;
}
