// HybridNitroServer — WindowsNativeImpl.cpp implementation.
// Generated by nitrogen link. Fill in the method bodies.
#include "../../lib/src/generated/cpp/nitro_server.native.g.h"

#include <string>

class HybridNitroServerImpl final : public HybridNitroServer {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroServer
};

// MSVC static-initializer auto-registration (no __attribute__((constructor)) on Windows).
namespace {
  struct _AutoRegister {
    _AutoRegister() { nitro_server_register_impl(new HybridNitroServerImpl()); }
  };
  static _AutoRegister _auto_register_instance;
}
