// HybridNitroServer — LinuxNativeImpl.cpp implementation.
// Generated by nitrogen init. Fill in the method bodies.
#include "../../lib/src/generated/cpp/nitro_server.native.g.h"

#include <string>

class HybridNitroServerImpl final : public HybridNitroServer {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroServer
};

// GCC/Clang auto-registration via constructor attribute.
__attribute__((constructor))
static void nitro_auto_register() {
    nitro_server_register_impl(new HybridNitroServerImpl());
}
