package dev.shreeman.nitro_server

import nitro.nitro_server_module.HybridNitroServerSpec

/// Native implementation of HybridNitroServerSpec.
/// This file is yours to edit — the interface is generated by `nitrogen generate`.
/// Use `applicationContext` (from the interface) to access the Android context.
class NitroServerImpl : HybridNitroServerSpec {

    override fun add(a: Double, b: Double): Double = a + b

    override suspend fun getGreeting(name: String): String = "Hello, $name!"
}
