// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.6
// Generated from: nitro_server.native.dart
// spec-sha256: 4fccf9467b8e1e46208ed03e534356cf33a88d064ad7fa88215159535d3bd125
// NativeImpl: cpp — shared C++ virtual-dispatch bridge (no JNI / Swift).
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#include <string>
#include <stdexcept>
#include "dart_api_dl.h"
#include "nitro_server.bridge.g.h"
#include "nitro_completion_batch.h"
static NitroCompletionBatch g_nitro_batch_nitro_server;
extern "C" {
NITRO_EXPORT bool nitro_server_nitro_post(int64_t port, struct _Dart_CObject* obj) { return g_nitro_batch_nitro_server.post(port, obj); }
NITRO_EXPORT int64_t nitro_server_nitro_bind(int64_t batchPort) { return g_nitro_batch_nitro_server.bind(batchPort); }
NITRO_EXPORT void nitro_server_nitro_ack(int64_t batchPort) { g_nitro_batch_nitro_server.ack(batchPort); }
}

#include "nitro_server.native.g.h"

extern "C" {
NITRO_EXPORT uint32_t nitro_server_nitro_abi_version(void) {
    return 1;
}
NITRO_EXPORT const char* nitro_server_nitro_bridge_checksum(void) {
    return "5f00625a4833a3e3";
}
NITRO_EXPORT intptr_t nitro_server_init_dart_api_dl(void* data) {
    return Dart_InitializeApiDL(data);
}
}

static thread_local NitroError g_nitro_error = { 0, nullptr, nullptr, nullptr, nullptr };
alignas(8) static thread_local uint8_t _g_opt_ret[16];
static thread_local std::string _g_str_ret;
// Deep copies of returned structs: Dart frees every pointer field.
[[maybe_unused]] static RawBodyChunk _nitro_clone_RawBodyChunk(const RawBodyChunk& _s);
[[maybe_unused]] static RawWsMessage _nitro_clone_RawWsMessage(const RawWsMessage& _s);
[[maybe_unused]] static RawBodyChunk _nitro_clone_RawBodyChunk(const RawBodyChunk& _s) {
    RawBodyChunk _c = _s;
    return _c;
}
[[maybe_unused]] static RawWsMessage _nitro_clone_RawWsMessage(const RawWsMessage& _s) {
    RawWsMessage _c = _s;
    return _c;
}


extern "C" {
NitroError* nitro_server_get_error() { return &g_nitro_error; }
void nitro_server_clear_error() {
    if (!g_nitro_error.hasError) { return; }
    g_nitro_error.hasError = 0;
    if (g_nitro_error.name)       { free((void*)g_nitro_error.name);       g_nitro_error.name       = nullptr; }
    if (g_nitro_error.message)    { free((void*)g_nitro_error.message);    g_nitro_error.message    = nullptr; }
    if (g_nitro_error.code)       { free((void*)g_nitro_error.code);       g_nitro_error.code       = nullptr; }
    if (g_nitro_error.stackTrace) { free((void*)g_nitro_error.stackTrace); g_nitro_error.stackTrace = nullptr; }
}
static void nitro_report_error(const char* name, const char* message, const char* code, const char* stack) {
    nitro_server_clear_error();
    g_nitro_error.hasError = 1;
    g_nitro_error.name       = name    ? strdup(name)    : strdup("NativeException");
    g_nitro_error.message    = message ? strdup(message) : strdup("An unknown C++ exception occurred.");
    g_nitro_error.code       = code    ? strdup(code)    : nullptr;
    g_nitro_error.stackTrace = stack   ? strdup(stack)   : nullptr;
}
}

#include <atomic>
#include <memory>
#include <mutex>
#include <unordered_map>

using HybridNitroServerNativeFactory = std::function<std::shared_ptr<HybridNitroServerNative>(const std::string&)>;
static std::unordered_map<int64_t, std::shared_ptr<HybridNitroServerNative>>& _g_instances() {
    static std::unordered_map<int64_t, std::shared_ptr<HybridNitroServerNative>> m;
    return m;
}
static std::mutex& _g_instances_mtx() {
    static std::mutex m;
    return m;
}
static std::atomic<int64_t>& _g_next_instance_id() {
    static std::atomic<int64_t> id{1};
    return id;
}
static HybridNitroServerNativeFactory& _g_factory() {
    static HybridNitroServerNativeFactory f;
    return f;
}

static constexpr int _kNitroCacheWays = 8;
struct alignas(64) _NitroInstSlot {
    std::atomic<int64_t> id{-1};
    std::atomic<HybridNitroServerNative*> ptr{nullptr};
};
static _NitroInstSlot _g_inst_cache[_kNitroCacheWays];
static HybridNitroServerNative* _nitro_get_instance(int64_t id) {
    _NitroInstSlot& _slot = _g_inst_cache[(uint64_t)id & (_kNitroCacheWays - 1)];
    if (_slot.id.load(std::memory_order_acquire) == id) {
        return _slot.ptr.load(std::memory_order_relaxed);
    }
    std::lock_guard<std::mutex> _lk(_g_instances_mtx());
    auto it = _g_instances().find(id);
    HybridNitroServerNative* p = (it != _g_instances().end()) ? it->second.get() : nullptr;
    if (p) {
        _slot.ptr.store(p, std::memory_order_relaxed);
        _slot.id.store(id, std::memory_order_release);
    }
    return p;
}
static void _nitro_invalidate_cache() {
    for (int _i = 0; _i < _kNitroCacheWays; ++_i) {
        _g_inst_cache[_i].id.store(-1, std::memory_order_release);
        _g_inst_cache[_i].ptr.store(nullptr, std::memory_order_relaxed);
    }
}

// Defined with the stream registries below (which may be emitted after
// this block): drops every subscriber belonging to one instance.
void _nitro_release_instance_streams(const void* impl);

extern "C" {
void nitro_server_register_factory(void* fn) {
    _g_factory() = *static_cast<HybridNitroServerNativeFactory*>(fn);
}
void nitro_server_register_impl(HybridNitroServerNative* impl) {
    std::lock_guard<std::mutex> _lk(_g_instances_mtx());
    if (impl) _g_instances()[0] = std::shared_ptr<HybridNitroServerNative>(impl, [](HybridNitroServerNative*){});
    else _g_instances().erase(0);
    _nitro_invalidate_cache();
}
HybridNitroServerNative* nitro_server_get_impl() {
    return _nitro_get_instance(0);
}
NITRO_EXPORT int64_t nitro_server_create_instance(const char* key) {
    if (_g_factory()) {
        auto inst = _g_factory()(key ? key : "");
        if (!inst) return -1;
        std::lock_guard<std::mutex> _lk(_g_instances_mtx());
        int64_t id = ++_g_next_instance_id();
        _g_instances()[id] = std::move(inst);
        return id;
    }
      // Legacy: no factory registered — return 0 (single global impl slot)
    return 0;
}
NITRO_EXPORT void nitro_server_destroy_instance(int64_t instanceId) {
    // Slot 0 belongs to register_impl (the legacy single impl and the
    // stream-emitter target), never to a Dart instance. Without this a
    // plugin that registers no factory hands every instance id 0, and the
    // first dispose() erases the slot for all of them.
    if (instanceId == 0) { return; }
    std::lock_guard<std::mutex> _lk(_g_instances_mtx());
    auto _it = _g_instances().find(instanceId);
    if (_it != _g_instances().end()) {
        _nitro_release_instance_streams(_it->second.get());
    }
    _g_instances().erase(instanceId);
    _nitro_invalidate_cache();
}
NITRO_EXPORT void nitro_server_nitro_free(void* ptr) { if (ptr) { free(ptr); } }
NITRO_EXPORT void* nitro_server_nitro_alloc(size_t size) { return malloc(size); }
NITRO_EXPORT void nitro_server_release_typed_data_return(void* ptr) {
    if (!ptr) { return; }
    int64_t* words = (int64_t*)ptr;
    void* payload = (void*)(intptr_t)words[1];
    if (payload && payload != ptr) { free(payload); }
    free(ptr);
}
}

#include <algorithm>
#include <mutex>
#include <unordered_map>
#include <vector>

// One registry per stream, PARTITIONED BY INSTANCE: a stream belongs to
// the Hybrid<Class> that emits it, so a subscriber on one instance never
// receives another instance's events (the ports used to be global, so
// every subscriber saw every instance). Every concurrent Dart subscriber
// registers its own ReceivePort. Guarded by a mutex — register/release
// run on the Dart isolate thread while emits may come from any thread.
struct _NitroStreamPorts {
    std::mutex mtx;
    std::unordered_map<const void*, std::vector<int64_t>> byInstance;
    void add(const void* inst, int64_t p) {
        std::lock_guard<std::mutex> l(mtx); byInstance[inst].push_back(p);
    }
    // Release carries only the port: Dart cancels a subscription without
    // naming the instance, so drop it wherever it is registered.
    void remove(int64_t p) {
        std::lock_guard<std::mutex> l(mtx);
        for (auto& kv : byInstance) {
            auto& v = kv.second;
            v.erase(std::remove(v.begin(), v.end(), p), v.end());
        }
    }
    void dropInstance(const void* inst) {
        std::lock_guard<std::mutex> l(mtx); byInstance.erase(inst);
    }
    std::vector<int64_t> snapshot(const void* inst) {
        std::lock_guard<std::mutex> l(mtx);
        auto it = byInstance.find(inst);
        return it == byInstance.end() ? std::vector<int64_t>() : it->second;
    }
};
static _NitroStreamPorts g_ports_incomingRequests;
static _NitroStreamPorts g_ports_bodyChunks;
static _NitroStreamPorts g_ports_serverEvents;
static _NitroStreamPorts g_ports_wsMessages;

// Called by destroy_instance so a disposed instance leaves no subscribers.
void _nitro_release_instance_streams(const void* impl) {
    g_ports_incomingRequests.dropInstance(impl);
    g_ports_bodyChunks.dropInstance(impl);
    g_ports_serverEvents.dropInstance(impl);
    g_ports_wsMessages.dropInstance(impl);
}

void HybridNitroServerNative::emit_incomingRequests(NitroCppBuffer item) {
    auto _ports = g_ports_incomingRequests.snapshot(this);
    if (_ports.empty()) { if (item.data) { free((void*)item.data); } return; }
    Dart_CObject obj;
    if (item.data == nullptr) {
        obj.type = Dart_CObject_kNull;
        for (int64_t _port : _ports) {
            if (!Dart_PostCObject_DL(_port, &obj)) { g_ports_incomingRequests.remove(_port); }
        }
        return;
    }
    for (int64_t _port : _ports) {
        uint8_t* _copy = (uint8_t*)malloc(item.size);
        if (!_copy) { break; }
        memcpy(_copy, item.data, item.size);
        obj.type = Dart_CObject_kInt64;
        obj.value.as_int64 = (intptr_t)_copy;
        if (!Dart_PostCObject_DL(_port, &obj)) {
            free(_copy);
            g_ports_incomingRequests.remove(_port);
        }
    }
    free((void*)item.data);
}

void HybridNitroServerNative::emit_bodyChunks(RawBodyChunk item) {
    auto _ports = g_ports_bodyChunks.snapshot(this);
    if (_ports.empty()) { return; }
    Dart_CObject obj;
    for (int64_t _port : _ports) {
        RawBodyChunk* st_ptr = (RawBodyChunk*)malloc(sizeof(RawBodyChunk));
        if (!st_ptr) { break; }
        *st_ptr = item;
        obj.type = Dart_CObject_kInt64;
        obj.value.as_int64 = (intptr_t)st_ptr;
        if (!Dart_PostCObject_DL(_port, &obj)) {
            free(st_ptr);
            g_ports_bodyChunks.remove(_port);
        }
    }
}

void HybridNitroServerNative::emit_serverEvents(NitroCppBuffer item) {
    auto _ports = g_ports_serverEvents.snapshot(this);
    if (_ports.empty()) { if (item.data) { free((void*)item.data); } return; }
    Dart_CObject obj;
    if (item.data == nullptr) {
        obj.type = Dart_CObject_kNull;
        for (int64_t _port : _ports) {
            if (!Dart_PostCObject_DL(_port, &obj)) { g_ports_serverEvents.remove(_port); }
        }
        return;
    }
    for (int64_t _port : _ports) {
        uint8_t* _copy = (uint8_t*)malloc(item.size);
        if (!_copy) { break; }
        memcpy(_copy, item.data, item.size);
        obj.type = Dart_CObject_kInt64;
        obj.value.as_int64 = (intptr_t)_copy;
        if (!Dart_PostCObject_DL(_port, &obj)) {
            free(_copy);
            g_ports_serverEvents.remove(_port);
        }
    }
    free((void*)item.data);
}

void HybridNitroServerNative::emit_wsMessages(RawWsMessage item) {
    auto _ports = g_ports_wsMessages.snapshot(this);
    if (_ports.empty()) { return; }
    Dart_CObject obj;
    for (int64_t _port : _ports) {
        RawWsMessage* st_ptr = (RawWsMessage*)malloc(sizeof(RawWsMessage));
        if (!st_ptr) { break; }
        *st_ptr = item;
        obj.type = Dart_CObject_kInt64;
        obj.value.as_int64 = (intptr_t)st_ptr;
        if (!Dart_PostCObject_DL(_port, &obj)) {
            free(st_ptr);
            g_ports_wsMessages.remove(_port);
        }
    }
}

// S8 helper — writes error info to the out-param slot.
static void _nitro_out_err(NitroError* e, const char* name, const char* msg) {
    if (!e) return;
    e->hasError = 1;
    e->name       = name ? strdup(name) : nullptr;
    e->message    = msg  ? strdup(msg)  : nullptr;
    e->code       = nullptr;
    e->stackTrace = nullptr;
}

extern "C" {

const char* nitro_server_engine_version(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return nullptr; }
    try {
        std::string _res = _impl->engineVersion();
        _g_str_ret = _res; return const_cast<char*>(_g_str_ret.c_str());
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return nullptr;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return nullptr;
    }
}

int8_t nitro_server_supports_tls(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return false; }
    try {
        return _impl->supportsTls();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return false;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return false;
    }
}

void nitro_server_reset_native(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return; }
    try {
        _impl->resetNative();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

int8_t nitro_server_supports_brotli(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return false; }
    try {
        return _impl->supportsBrotli();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return false;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return false;
    }
}

uint8_t* nitro_server_brotli_encode(int64_t instanceId, uint8_t* data, size_t data_length, int64_t quality, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return nullptr; }
    try {
        NitroCppBuffer _res = _impl->brotliEncode(data, static_cast<size_t>(data_length), quality);
        if (_res.size > (size_t)INT64_MAX || (_res.size > 0 && _res.data == nullptr)) {
            nitro_report_error("ArgumentError", "brotliEncode: @zeroCopy return buffer has invalid data/size", nullptr, nullptr);
            return nullptr;
        }
        int64_t* _env = (int64_t*)malloc(sizeof(int64_t) * 3);
        if (_env == nullptr) {
            nitro_report_error("OutOfMemoryError", "brotliEncode: failed to allocate zero-copy return envelope", nullptr, nullptr);
            return nullptr;
        }
        _env[0] = (int64_t)_res.size;
        _env[1] = (int64_t)(intptr_t)(_res.data != nullptr ? _res.data : (const uint8_t*)_env);
        _env[2] = 0;
        return (uint8_t*)_env;
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return nullptr;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return nullptr;
    }
}

uint8_t* nitro_server_brotli_decode(int64_t instanceId, uint8_t* data, size_t data_length, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return nullptr; }
    try {
        NitroCppBuffer _res = _impl->brotliDecode(data, static_cast<size_t>(data_length));
        if (_res.size > (size_t)INT64_MAX || (_res.size > 0 && _res.data == nullptr)) {
            nitro_report_error("ArgumentError", "brotliDecode: @zeroCopy return buffer has invalid data/size", nullptr, nullptr);
            return nullptr;
        }
        int64_t* _env = (int64_t*)malloc(sizeof(int64_t) * 3);
        if (_env == nullptr) {
            nitro_report_error("OutOfMemoryError", "brotliDecode: failed to allocate zero-copy return envelope", nullptr, nullptr);
            return nullptr;
        }
        _env[0] = (int64_t)_res.size;
        _env[1] = (int64_t)(intptr_t)(_res.data != nullptr ? _res.data : (const uint8_t*)_env);
        _env[2] = 0;
        return (uint8_t*)_env;
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return nullptr;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return nullptr;
    }
}

void nitro_server_configure_server(int64_t instanceId, void* config, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return; }
    try {
        NitroCppBuffer _buf_config = { (const uint8_t*)config + 4, (size_t)*(int32_t*)config };
        _impl->configureServer(_buf_config);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void* nitro_server_register_route(int64_t instanceId, void* route, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return nullptr; }
    try {
        NitroCppBuffer _buf_route = { (const uint8_t*)route + 4, (size_t)*(int32_t*)route };
        NitroCppBuffer _res = _impl->registerRoute(_buf_route);
        return (uint8_t*)_res.data;
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return nullptr;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return nullptr;
    }
}

void* nitro_server_unregister_route(int64_t instanceId, const char* method, const char* pattern, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return nullptr; }
    try {
        NitroCppBuffer _res = _impl->unregisterRoute(std::string(method), std::string(pattern));
        return (uint8_t*)_res.data;
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return nullptr;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return nullptr;
    }
}

void* nitro_server_register_static_route(int64_t instanceId, const char* method, const char* pattern, int64_t status, void* headers, uint8_t* body, size_t body_length, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return nullptr; }
    try {
        NitroCppBuffer _buf_headers = { (const uint8_t*)headers + 4, (size_t)*(int32_t*)headers };
        NitroCppBuffer _res = _impl->registerStaticRoute(std::string(method), std::string(pattern), status, _buf_headers, body, static_cast<size_t>(body_length));
        return (uint8_t*)_res.data;
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return nullptr;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return nullptr;
    }
}

void* nitro_server_start(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return nullptr; }
    try {
        NitroCppBuffer _res = _impl->start();
        return (uint8_t*)_res.data;
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return nullptr;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return nullptr;
    }
}

void nitro_server_stop(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return; }
    try {
        _impl->stop();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_server_begin_drain(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return; }
    try {
        _impl->beginDrain();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

int64_t nitro_server_in_flight_requests(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return 0; }
    try {
        return _impl->inFlightRequests();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return 0;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return 0;
    }
}

int64_t nitro_server_live_connections(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return 0; }
    try {
        return _impl->liveConnections();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return 0;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return 0;
    }
}

void nitro_server_respond_file(int64_t instanceId, int64_t requestId, int64_t status, void* headers, const char* path, int64_t offset, int64_t length, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return; }
    try {
        NitroCppBuffer _buf_headers = { (const uint8_t*)headers + 4, (size_t)*(int32_t*)headers };
        _impl->respondFile(requestId, status, _buf_headers, std::string(path), offset, length);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_server_respond(int64_t instanceId, int64_t requestId, int64_t status, void* headers, uint8_t* body, size_t body_length, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return; }
    try {
        NitroCppBuffer _buf_headers = { (const uint8_t*)headers + 4, (size_t)*(int32_t*)headers };
        _impl->respond(requestId, status, _buf_headers, body, static_cast<size_t>(body_length));
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_server_ack_body(int64_t instanceId, int64_t requestId, int64_t ackedChunks, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return; }
    try {
        _impl->ackBody(requestId, ackedChunks);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_server_start_stream(int64_t instanceId, int64_t requestId, int64_t status, void* headers, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return; }
    try {
        NitroCppBuffer _buf_headers = { (const uint8_t*)headers + 4, (size_t)*(int32_t*)headers };
        _impl->startStream(requestId, status, _buf_headers);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_server_send_stream_chunk(int64_t instanceId, int64_t requestId, uint8_t* chunk, size_t chunk_length, int8_t last, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return; }
    try {
        _impl->sendStreamChunk(requestId, chunk, static_cast<size_t>(chunk_length), last);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

int64_t nitro_server_ws_send(int64_t instanceId, int64_t connectionId, uint8_t* payload, size_t payload_length, int8_t binary, int8_t compressed, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return 0; }
    try {
        return _impl->wsSend(connectionId, payload, static_cast<size_t>(payload_length), binary, compressed);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return 0;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return 0;
    }
}

void nitro_server_ws_close(int64_t instanceId, int64_t connectionId, int64_t code, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_server_register_factory() or nitro_server_register_impl()."); return; }
    try {
        _impl->wsClose(connectionId, code);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_server_register_incoming_requests_stream(int64_t instanceId, int64_t dart_port) {
    g_nitro_batch_nitro_server.coalesce(dart_port);
    g_ports_incomingRequests.add(_nitro_get_instance(instanceId), dart_port);
}
void nitro_server_release_incoming_requests_stream(int64_t dart_port) {
    g_ports_incomingRequests.remove(dart_port);
    g_nitro_batch_nitro_server.uncoalesce(dart_port);
}

void nitro_server_register_body_chunks_stream(int64_t instanceId, int64_t dart_port) {
    g_ports_bodyChunks.add(_nitro_get_instance(instanceId), dart_port);
}
void nitro_server_release_body_chunks_stream(int64_t dart_port) {
    g_ports_bodyChunks.remove(dart_port);
}

void nitro_server_register_server_events_stream(int64_t instanceId, int64_t dart_port) {
    g_ports_serverEvents.add(_nitro_get_instance(instanceId), dart_port);
}
void nitro_server_release_server_events_stream(int64_t dart_port) {
    g_ports_serverEvents.remove(dart_port);
}

void nitro_server_register_ws_messages_stream(int64_t instanceId, int64_t dart_port) {
    g_ports_wsMessages.add(_nitro_get_instance(instanceId), dart_port);
}
void nitro_server_release_ws_messages_stream(int64_t dart_port) {
    g_ports_wsMessages.remove(dart_port);
}

// Frees a malloc'd [RawBodyChunk] wrapper allocated by the stream emitter.
// Called automatically by NativeFinalizer when the Dart proxy is GC'd.
void nitro_server_release_RawBodyChunk(void* ptr) {
    if (!ptr) { return; }
    free(ptr);
}

// Frees a malloc'd [RawWsMessage] wrapper allocated by the stream emitter.
// Called automatically by NativeFinalizer when the Dart proxy is GC'd.
void nitro_server_release_RawWsMessage(void* ptr) {
    if (!ptr) { return; }
    free(ptr);
}

} // extern "C"
