// HybridNitroServer — NativeImpl.cpp implementation.
// Generated by nitrogen link. Fill in the method bodies.
#include "../lib/src/generated/cpp/nitro_server.native.g.h"

#include <string>

class HybridNitroServerImpl final : public HybridNitroServer {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroServer
};

static HybridNitroServerImpl g_impl;

// Auto-register on shared library load — no manual init call needed.
#if defined(_WIN32) || (defined(__linux__) && !defined(__ANDROID__))
#if defined(_WIN32)
namespace {
  struct _AutoRegister {
    _AutoRegister() { nitro_server_register_impl(&g_impl); }
  };
  _AutoRegister _auto_register_instance;
}
#else
__attribute__((constructor))
static void nitro_server_auto_register() {
    nitro_server_register_impl(&g_impl);
}
#endif
#endif // auto-register on C++ platforms
